{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mneme.fullname" . }}-auth
  namespace: {{ include "mneme.namespace" . }}
  labels:
    {{- include "mneme.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin_password: {{ .Values.auth.adminPassword | required "auth.adminPassword is required" | quote }}
  cluster_secret:  {{ .Values.auth.clusterSecret  | required "auth.clusterSecret is required"  | quote }}
{{- end }}
